---
#- name: stop services
#  service: name={{ item }} state=stopped enabled=no
#  with_items:
#    - nginx

- name: install supervisor
  apt: pkg=supervisor state=present update_cache=true

- name: installing gunicorn start script
  template: src=start_gunicorn.sh.j2 dest={{ virtualenv_path }}/bin/start_gunicorn.sh
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0700


  with_items: tasks
- name: installing tasks
  template: src={{ item }}.conf.j2 dest={{ supervisor_config_dir }}/{{ item }}.conf
  with_items: tasks

#- name: Disable Nginx on startup
#  raw: "update-rc.d -f nginx disable && mv /etc/init.d/nginx /etc/init.d/nginx_disabled"

- name: create log dir
  file: path={{ application_log_dir }} state=directory
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}

- name: Start supervisor
  service: name=supervisor state=started enabled=yes

- name: update supervisor
  command: "{{ supervisorctl_command }} update"

- name: restart tasks
  command: "{{ supervisorctl_command }} restart {{ item }}:*"
  with_items: tasks
