---

git_repo: 'git@github.com:cosmopolithome/cosmoserver.git'
application_name: 'cosmoserver'
application_log_dir: "/var/log/{{ application_name }}"
application_log_file_base: "{{ application_log_dir }}/supervisor-gunicorn"
project_name: 'cosmopolithome'
app_user: 'cosmo'
app_group: "{{ app_user }}"
virtualenv_path: "/home/{{ app_user }}/.virtualenvs/{{ application_name }}"
git_project_path: "/home/{{ app_user }}/{{ application_name }}"
application_path: "{{ git_project_path }}"

ssl_dest_dir: /etc/ssl

ssl_crt: |
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----

# This key is for demo purposes only. If you're committing your keys
# to your git repo, you'd probably want it encrypted. You can use
# ansible-vault to do this.
ssl_key: |
  -----BEGIN PRIVATE KEY-----
  -----END PRIVATE KEY-----

common_hostname: "{{ env_type }}-{{ project_name }}-django-server"
  
base_url: cosmopolithome.com
media_url: "http://media.{{ base_url }}"
prerender_token: yMXuziDPSih49x32QYe2
