---

env_type: 'dev'
# Database settings.
db_host: "cosmo-pg-rds.cickmf1tzggl.eu-west-1.rds.amazonaws.com"
db_port: "5432"
db_user: "{{ app_user }}"
db_name: "{{ app_user }}"
db_password: password

#REDIS
redis_host: "cosmo-redis.yompsh.0001.euw1.cache.amazonaws.com"
redis_port: "6379"
redis_password:


# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0
gunicorn_log_level: debug

# SMTP settings.
smtp_host: smtp.gmail.com
smtp_user: admin@example.com
smtp_password: mypassword

# Application settings.
django_secret_key: _e@do%6+-f)s&xd$z17y2a_7&%t3+*kpt8s+gcosrpj6r1$k$0

run_django_syncdb: no
run_django_south_migration: no
run_django_collectstatic: no
setup_git_repo: yes

base_url: cosmopolithome.{{ env_type }}
media_url: "http://media.{{ base_url }}"
prerender_token: yMXuziDPSih49x32QYe2
