---
- name: Install dependences
  apt: name={{item}} state=present
  with_items:
    - postgresql-client
    - binutils
    - libproj-dev
    - gdal-bin

- name: Create pgpass file
  template: src=pgpass.j2 dest=/home/{{ app_user }}/.pgpass
    owner={{ app_user }}
    group={{ app_user }}
    mode=0600


- name: Active postgis
  sudo: yes
  sudo_user: "{{ app_user }}"
  command: psql -c 'create extension IF NOT EXISTS postgis;' -d {{ db_name }} -h {{ db_host }} 

