---
- name: Create directorys
  copy: src={{ item }}  dest=/etc/nginx
  with_items:
    - certs
    - global
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create time_log_format
  copy: src=time_log.conf dest=/etc/nginx/conf.d/time_log.conf
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create global conf
  template: src=global/{{ item }}.j2 dest=/etc/nginx/global/{{ item }}
  with_items: globals
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create the configurations for sites
  template: src=sites-available/{{ item }}.conf.j2 dest=/etc/nginx/sites-available/{{ item }}.conf
  with_items: sites
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create links for sites-enabled
  file: state=link src=/etc/nginx/sites-available/{{ item }}.conf dest=/etc/nginx/sites-enabled/{{ item }}.conf
  with_items: sites
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Check nginx syntax of configuration files
  shell: nginx -t
  register: result
  changed_when: "result.rc != 0"
  always_run: yes
  tags: [configuration,nginx]

- name: Start the nginx service
  service: name=nginx state=started enabled=yes
  tags: [service,nginx]
