---
galaxy_info:
  author: "Christophe Chaudier"
  company: 
  license: MIT
  min_ansible_version: 1.4
  platforms:
   - name: Ubuntu
     versions:
      - precise
  categories:
   - web
dependencies: []
  
